# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: go-todo
    ports:
      - "5432:5432"
    command: -p 5432


 